"""create user and blog table

Revision ID: 080a1569e81c
Revises: 5b17610477b2
Create Date: 2024-06-05 00:53:37.759182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080a1569e81c'
down_revision = '5b17610477b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
